<?php

require_once './templates/layout/header.phtml';
    
?>
<h1>AGREGA UNA CANCION NUEVA</h1>
<?php
require_once './templates/form.add.canciones.phtml';
?>

<ul class="list-group">
    <h2>CANCIONES</h2>
<?php foreach($tasks_canciones as $task_cancione) { ?>
    <li class="list-group-item item-task">
        <div>
            <b> <?php echo $task_cancione->nombre_cancion ?></b> | <?php echo $task_cancione->top_cancion ?> | <?php echo $task_cancione->duracion ?> | <?php echo $task_cancione->genero ?>
        </div>
        <div class="actions">
            <a href="eliminar_cancion/<?php echo $task_cancione->id_cancion ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
        </div>
    </li>
<?php } ?>
</ul>

<?php
require_once './templates/layout/footer.phtml';