<?php require_once './templates/layout/header.phtml';?>  

<form action="login" method="POST" class="my-4">

    <?php if ($error): ?>
        <div class='alert alert-danger' role='alert'>
            <?= $error ?>
        </div>
    <?php endif ?>


    <div>
        <div class="col-9">
            <div class="form-group">
                <label for="email">Ingrese email</label>
                <input id="email" required name="email" type="email" class="form-control">
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label for="password">Ingrese password</label>
                <input id="password" required name="password" type="password" class="form-control">
            </div>
        </div>

    </div>

    <button type="submit" class="btn btn-primary mt-2">Login</button>

</form>

<?php require_once './templates/layout/footer.phtml'; ?>